#!/usr/bin/env python3
"""Regenerates shared/tests/rules_vectors.json from the reference implementation.

    python3 shared/tools/generate_vectors.py

Run it after changing a rule in GAME_RULES.md (and reference_rules.py) or a value in
shared/config. Both engines' test suites replay the result.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import reference_rules as R  # noqa: E402

data = R.load_all()
game = data["game"]
eco, combat, mov, match = game["economy"], game["combat"], game["movement"], game["match"]
weapons = {w["id"]: w for w in data["weapons"]["weapons"]}
agents = {a["id"]: a for a in data["agents"]["agents"]}
V = {"_comment": "Generated by shared/tools/generate_vectors.py from reference_rules.py. Do not edit by hand."}

# economy -------------------------------------------------------------------
V["economy"] = []
for won in (True, False):
    for streak in (0, 1, 2, 3, 4, 7):
        for att in (True, False):
            for planted in (False, True):
                if won and streak:
                    continue
                V["economy"].append({"won": won, "lossStreak": streak, "isAttacker": att, "bombPlanted": planted,
                                     "expected": R.round_income(eco, won, streak, att, planted)})
V["killReward"] = [{"weaponId": wid, "expected": R.kill_reward(eco, w)} for wid, w in weapons.items()]
V["killReward"].append({"weaponId": "", "expected": R.kill_reward(eco, None)})

# damage --------------------------------------------------------------------
V["hitZone"] = []
for height in (1.8, 1.2):
    for frac in (0.1, 0.415, 0.425, 0.6, 0.835, 0.845, 0.99):
        V["hitZone"].append({"hitHeight": round(frac * height, 6), "height": height,
                             "expected": R.hit_zone(combat, round(frac * height, 6), height)})
V["damage"] = []
for wid in ("p9", "magnum", "wasp", "breacher", "valkyrie", "kestrel", "sentinel", "longbow", "knife"):
    w = weapons[wid]
    for zone in ("head", "body", "legs"):
        for dist in (5.0, 12.0, 22.5, 40.0):
            for armor in (0, 25, 50):
                for mult in (1.0, 0.5):
                    if mult != 1.0 and armor != 50:
                        continue
                    raw = R.raw_damage(w, zone, dist)
                    hp, ar = R.apply_armor(combat, raw, armor, w["armorPenetration"], mult)
                    V["damage"].append({"weaponId": wid, "zone": zone, "distance": dist, "armor": armor,
                                        "damageTakenMultiplier": mult, "expectedHealth": hp, "expectedArmor": ar})
V["areaDamage"] = []
for raw in (0.0, 33.3, 55.5, 110.0, 500.0):
    for armor in (0, 50):
        for pen in (0.0, 1.0):
            hp, ar = R.apply_armor(combat, raw, armor, pen)
            V["areaDamage"].append({"raw": raw, "armor": armor, "armorPenetration": pen,
                                    "expectedHealth": hp, "expectedArmor": ar})

# weapons -------------------------------------------------------------------
V["spread"] = []
for wid in ("p9", "wasp", "valkyrie", "longbow", "breacher"):
    w = weapons[wid]
    for speed in (0.0, 3.3, 6.0, 9.0):
        for airborne, crouched, aiming in ((False, False, False), (False, True, False), (False, False, True),
                                           (True, False, False), (True, True, True)):
            for shot in (0, 3, 30):
                V["spread"].append({"weaponId": wid, "speed": speed, "airborne": airborne, "crouched": crouched,
                                    "aiming": aiming, "shotIndex": shot,
                                    "expected": round(R.spread(w, mov, speed, airborne, crouched, aiming, shot), 6)})
V["recoil"] = []
for wid in ("valkyrie", "kestrel", "p9", "knife"):
    for shot in (0, 1, 5, 12, 50):
        p, y = R.recoil_kick(weapons[wid], shot)
        V["recoil"].append({"weaponId": wid, "shotIndex": shot, "expectedPitch": p, "expectedYaw": y})

# round end + match flow ----------------------------------------------------
V["roundEnd"] = []
for det in (False, True):
    for dfs in (False, True):
        for planted in (False, True):
            for att in (0, 2):
                for dfn in (0, 3):
                    for tl in (10.0, 0.0):
                        if (det or dfs) and not planted:
                            continue
                        side, reason = R.evaluate_round_end(det, dfs, planted, att, dfn, tl)
                        V["roundEnd"].append({"detonated": det, "defused": dfs, "planted": planted,
                                              "aliveAttackers": att, "aliveDefenders": dfn, "roundTimeLeft": tl,
                                              "expectedWinnerSide": side or "none", "expectedReason": reason})


def flow_case(name, winners, start_side="attack", **overrides):
    m = dict(match)
    m.update(overrides)
    f = R.MatchFlow(m, start_side)
    for i, ch in enumerate(winners):
        if f.winner is not None:
            raise SystemExit(f"{name}: match ended before round {i + 1}")
        f.end_round(0 if ch == "A" else 1)
    if f.winner is None:
        raise SystemExit(f"{name}: match did not end")
    return {"name": name, "startSideA": start_side,
            "roundsToWin": m["roundsToWin"], "halftimeAfterRound": m["halftimeAfterRound"],
            "overtimeEnabled": m["overtimeEnabled"], "overtimeWinMargin": m["overtimeWinMargin"],
            "overtimeSwapEveryRounds": m["overtimeSwapEveryRounds"], "maxOvertimeRounds": m["maxOvertimeRounds"],
            "winners": winners,
            "expectedWinner": "draw" if f.winner == "draw" else ("A" if f.winner == 0 else "B"),
            "expectedRoundsPlayed": f.round, "expectedScoreA": f.score[0], "expectedScoreB": f.score[1],
            "expectedSwapsAfterRounds": f.swaps_after, "expectedResets": "".join(f.resets),
            "expectedFinalSideA": f.side_a, "expectedOvertime": f.overtime}


V["matchFlow"] = [
    flow_case("sweep", "A" * 13),
    flow_case("defense start sweep", "B" * 13, start_side="defense"),
    flow_case("second half comeback", "AAAAA" + "B" * 13),
    flow_case("overtime win", "AB" * 12 + "AA"),
    flow_case("overtime back and forth", "AB" * 12 + "AB" + "BB"),
    flow_case("overtime draw", "AB" * 12 + "AB" * 6),
    flow_case("draw without overtime", "AB" * 12, overtimeEnabled=False),
    flow_case("short match", "BBBA" + "AAAA", start_side="defense", roundsToWin=5, halftimeAfterRound=4),
    flow_case("short match overtime", "AB" * 4 + "BAAA", roundsToWin=5, halftimeAfterRound=4,
              overtimeSwapEveryRounds=2, maxOvertimeRounds=6),
]

# map + navigation ----------------------------------------------------------
V["maps"] = []
for mid, mdef in data["maps"].items():
    g = R.MapGrid(mdef)
    counts = {R.CELL_NAMES[t]: g.count(t) for t in range(8)}
    boxes = {R.CELL_NAMES[t]: len(g.boxes(t)) for t in range(8)}
    centers = []
    for (x, y) in ((0, 0), (g.w - 1, g.h - 1), (10, 5), (23, 17)):
        e, n = g.center(x, y)
        centers.append({"x": x, "y": y, "east": e, "north": n})
    cell_at = []
    for (e, n) in ((0.0, 0.0), (-47.9, 35.9), (47.9, -35.9), (3.1, -7.9), (-0.01, 0.01)):
        cx, cy = g.cell_at(e, n)
        cell_at.append({"east": e, "north": n, "expectedX": cx, "expectedY": cy})
    first_cell = {t: next(((x, y) for y in range(g.h) for x in range(g.w) if g.get(x, y) == t), None)
                  for t in (R.ATT_SPAWN, R.DEF_SPAWN, R.SITE_A, R.SITE_B)}
    paths = []
    pairs = [(R.ATT_SPAWN, R.SITE_A), (R.ATT_SPAWN, R.SITE_B), (R.DEF_SPAWN, R.SITE_A), (R.DEF_SPAWN, R.SITE_B),
             (R.ATT_SPAWN, R.DEF_SPAWN)]
    for a, b in pairs:
        (sx, sy), (gx, gy) = first_cell[a], first_cell[b]
        cost = R.astar(g, sx, sy, gx, gy)
        paths.append({"fromX": sx, "fromY": sy, "toX": gx, "toY": gy, "found": cost is not None,
                      "expectedCost": round(cost, 6) if cost is not None else -1})
    paths.append({"fromX": 1, "fromY": 1, "toX": 10, "toY": 10, "found": False, "expectedCost": -1})
    V["maps"].append({"mapId": mid, "width": g.w, "height": g.h, "cellCounts": counts, "boxCounts": boxes,
                      "centers": centers, "cellAt": cell_at, "paths": paths})

# rng + audio ---------------------------------------------------------------
V["rng"] = []
for seed in (0, 1, 12345, 0xDEADBEEF):
    r = R.Rng(seed)
    ints = [r.next() for _ in range(5)]
    r2 = R.Rng(seed)
    floats = [round(r2.next_float(), 9) for _ in range(5)]
    V["rng"].append({"seed": seed, "expectedInts": ints, "expectedFloats": floats})
V["hash"] = [{"text": t, "expected": R.fnv1a32(t)} for t in ("", "a", "shot_rifle", "bomb_beep")]
sr = data["audio"]["sampleRate"]
V["synth"] = []
for cue in data["audio"]["cues"]:
    if cue["id"] not in ("shot_rifle", "bomb_beep", "explosion", "hit_head", "footstep"):
        continue
    s = R.synth(cue, sr)
    idx = [0, 1, 7, len(s) // 3, len(s) // 2, len(s) - 1]
    V["synth"].append({"cueId": cue["id"], "sampleRate": sr, "expectedCount": len(s), "indices": idx,
                       "expectedValues": [round(s[i], 7) for i in idx]})

# shop ----------------------------------------------------------------------


def shop(name, agent_id, side, money, ops, primary=None, armor=0):
    ag = agents[agent_id]
    lo = R.Loadout(game["loadout"]["defaultSecondary"])
    lo.primary = primary
    lo.armor = armor
    steps = []
    start_money = money
    for op, item in ops:
        if op == "buy":
            res, money, dropped = R.shop_buy(data, ag, side, lo, money, item)
        else:
            res, money = R.shop_sell(data, ag, lo, money, item)
            dropped = None
        steps.append({"op": op, "item": item, "expectedResult": res, "expectedMoney": money,
                      "expectedDropped": dropped or "", "expectedPrimary": lo.primary or "",
                      "expectedSecondary": lo.secondary or "", "expectedArmor": lo.armor,
                      "expectedKit": lo.kit, "expectedCharges": list(lo.charges)})
    return {"name": name, "agentId": agent_id, "side": side, "initialMoney": start_money,
            "initialPrimary": primary or "", "initialArmor": armor, "steps": steps}


V["shop"] = [
    shop("pistol round", "vanguard", "attack", 800,
         [("buy", "light_shield"), ("buy", "flashbang"), ("buy", "flashbang"), ("buy", "flashbang"),
          ("buy", "magnum"), ("sell", "flashbang"), ("buy", "magnum"), ("buy", "knife"), ("buy", "overdrive"),
          ("buy", "dash")]),
    shop("full buy and swap", "warden", "defense", 5000,
         [("buy", "valkyrie"), ("buy", "kestrel"), ("buy", "heavy_shield"), ("buy", "defuse_kit"),
          ("buy", "defuse_kit"), ("buy", "smoke"), ("buy", "smoke"), ("buy", "smoke"), ("sell", "kestrel"),
          ("buy", "longbow"), ("sell", "heavy_shield"), ("buy", "light_shield")]),
    shop("replace carried rifle", "operator", "attack", 3000,
         [("buy", "kestrel"), ("buy", "defuse_kit"), ("buy", "heavy_shield"), ("sell", "kestrel"),
          ("buy", "wasp")], primary="valkyrie", armor=25),
    shop("broke", "seeker", "attack", 100,
         [("buy", "p9"), ("buy", "wasp"), ("buy", "recon_pulse"), ("buy", "orbital_scan"), ("sell", "wasp"),
          ("buy", "does_not_exist")]),
]

out = os.path.join(R.SHARED, "tests", "rules_vectors.json")
with open(out, "w", encoding="utf-8") as f:
    json.dump(V, f, indent=1)
    f.write("\n")
print("wrote", out, {k: (len(v) if isinstance(v, list) else 1) for k, v in V.items()})
