#!/usr/bin/env python3
"""Generates C++ for the Unreal core check from shared/ JSON.

build/generated_data.inc   - fills an FTSGameData from shared/config and shared/maps by
                             assigning every JSON key to the UPROPERTY of the same name
                             (first letter capitalised). If a key has no matching property
                             the compile fails, which proves FJsonObjectConverter will find
                             every key at runtime.
build/generated_vectors.inc - shared/tests/rules_vectors.json as C++ initialisers.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SHARED = os.path.join(HERE, "..", "..", "shared")
BUILD = os.path.join(HERE, "build")

# JSON array key -> element struct, by the name of the struct that contains it.
ARRAY_TYPES = {
    ("FTSWeaponList", "weapons"): "FTSWeaponDef",
    ("FTSWeaponDef", "recoilPattern"): "FTSRecoilStep",
    ("FTSEquipmentList", "equipment"): "FTSEquipmentDef",
    ("FTSAbilityList", "abilities"): "FTSAbilityDef",
    ("FTSAgentList", "agents"): "FTSAgentDef",
    ("FTSAgentDef", "abilities"): "FTSAgentAbilitySlot",
    ("FTSBotConfig", "difficulties"): "FTSBotDifficulty",
    ("FTSInputConfig", "bindings"): "FTSKeyBinding",
    ("FTSAudioConfig", "cues"): "FTSAudioCue",
    ("FTSUserSettings", "keyOverrides"): "FTSKeyBinding",
}
OBJECT_TYPES = {
    ("FTSGameConfig", k): "FTS" + v for k, v in {
        "match": "MatchSettings", "round": "RoundSettings", "economy": "EconomySettings", "bomb": "BombSettings",
        "movement": "MovementSettings", "combat": "CombatSettings", "ultimate": "UltimateSettings",
        "scoring": "ScoringSettings", "loadout": "LoadoutSettings", "visuals": "VisualSettings"}.items()
}
OBJECT_TYPES[("FTSBotConfig", "buy")] = "FTSBotBuySettings"
OBJECT_TYPES[("FTSBotConfig", "behaviour")] = "FTSBotBehaviourSettings"

counter = [0]


def prop(key):
    return key[0].upper() + key[1:]


def lit(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, str):
        return "FString(" + json.dumps(v) + ")"
    if isinstance(v, int):
        return str(v)
    return repr(float(v)) + "f"


def emit(out, struct, target, obj, indent="\t"):
    for key, value in obj.items():
        if key.startswith("_"):
            continue
        field = f"{target}.{prop(key)}"
        if isinstance(value, dict):
            emit(out, OBJECT_TYPES[(struct, key)], field, value, indent)
        elif isinstance(value, list):
            elem = ARRAY_TYPES.get((struct, key))
            for item in value:
                if elem is None:
                    out.append(f"{indent}{field}.Add({lit(item)});")
                else:
                    counter[0] += 1
                    var = f"E{counter[0]}"
                    out.append(f"{indent}{{ {elem} {var};")
                    emit(out, elem, var, item, indent + "\t")
                    out.append(f"{indent}  {field}.Add({var}); }}")
        else:
            out.append(f"{indent}{field} = {lit(value)};")


def load(rel):
    with open(os.path.join(SHARED, rel), encoding="utf-8") as f:
        return json.load(f)


def data_inc():
    out = ["// Generated by tools/ue-core-check/generate.py. Do not edit.", "static FTSGameData MakeGameData()", "{",
           "\tFTSGameData D;"]
    emit(out, "FTSGameConfig", "D.Game", load("config/game.json"))
    for name, list_struct, member in (("weapons", "FTSWeaponList", "Weapons"), ("equipment", "FTSEquipmentList", "Equipment"),
                                      ("abilities", "FTSAbilityList", "Abilities"), ("agents", "FTSAgentList", "Agents")):
        out.append(f"\t{{ {list_struct} L;")
        emit(out, list_struct, "L", load(f"config/{name}.json"), "\t\t")
        out.append(f"\t  D.{member} = L.{member}; }}")
    emit(out, "FTSBotConfig", "D.Bots", load("config/bots.json"))
    emit(out, "FTSInputConfig", "D.Input", load("config/input.json"))
    emit(out, "FTSAudioConfig", "D.Audio", load("config/audio.json"))
    emit(out, "FTSUserSettings", "D.DefaultSettings", load("config/settings.json"))
    for map_id in load("config/game.json")["mapRotation"]:
        out.append("\t{ FTSMapDef M;")
        emit(out, "FTSMapDef", "M", load(f"maps/{map_id}.json"), "\t\t")
        out.append("\t  D.Maps.Add(M); }")
    out += ["\treturn D;", "}"]
    return "\n".join(out) + "\n"


def c_bool(b):
    return "true" if b else "false"


def c_str(s):
    return json.dumps(s if s is not None else "")


def vectors_inc():
    v = load("tests/rules_vectors.json")
    o = ["// Generated by tools/ue-core-check/generate.py. Do not edit."]

    def table(ctype, name, rows):
        o.append(f"static const {ctype} {name}[] = {{")
        o.extend("\t{ " + ", ".join(r) + " }," for r in rows)
        o.append("};")

    table("FEconomyV", "GEconomy", [[c_bool(e["won"]), str(e["lossStreak"]), c_bool(e["isAttacker"]), c_bool(e["bombPlanted"]), str(e["expected"])] for e in v["economy"]])
    table("FKillRewardV", "GKillReward", [[c_str(e["weaponId"]), str(e["expected"])] for e in v["killReward"]])
    table("FHitZoneV", "GHitZone", [[repr(e["hitHeight"]), repr(e["height"]), c_str(e["expected"])] for e in v["hitZone"]])
    table("FDamageV", "GDamage", [[c_str(e["weaponId"]), c_str(e["zone"]), repr(e["distance"]), str(e["armor"]), repr(e["damageTakenMultiplier"]), str(e["expectedHealth"]), str(e["expectedArmor"])] for e in v["damage"]])
    table("FAreaDamageV", "GAreaDamage", [[repr(e["raw"]), str(e["armor"]), repr(e["armorPenetration"]), str(e["expectedHealth"]), str(e["expectedArmor"])] for e in v["areaDamage"]])
    table("FSpreadV", "GSpread", [[c_str(e["weaponId"]), repr(e["speed"]), c_bool(e["airborne"]), c_bool(e["crouched"]), c_bool(e["aiming"]), str(e["shotIndex"]), repr(e["expected"])] for e in v["spread"]])
    table("FRecoilV", "GRecoil", [[c_str(e["weaponId"]), str(e["shotIndex"]), repr(e["expectedPitch"]), repr(e["expectedYaw"])] for e in v["recoil"]])
    table("FRoundEndV", "GRoundEnd", [[c_bool(e["detonated"]), c_bool(e["defused"]), c_bool(e["planted"]), str(e["aliveAttackers"]), str(e["aliveDefenders"]), repr(e["roundTimeLeft"]), c_str(e["expectedWinnerSide"]), c_str(e["expectedReason"])] for e in v["roundEnd"]])
    table("FMatchFlowV", "GMatchFlow", [[c_str(e["name"]), c_str(e["startSideA"]), str(e["roundsToWin"]), str(e["halftimeAfterRound"]), c_bool(e["overtimeEnabled"]), str(e["overtimeWinMargin"]), str(e["overtimeSwapEveryRounds"]), str(e["maxOvertimeRounds"]), c_str(e["winners"]), c_str(e["expectedWinner"]), str(e["expectedRoundsPlayed"]), str(e["expectedScoreA"]), str(e["expectedScoreB"]), c_str(",".join(str(x) for x in e["expectedSwapsAfterRounds"])), c_str(e["expectedResets"]), c_str(e["expectedFinalSideA"]), c_bool(e["expectedOvertime"])] for e in v["matchFlow"]])
    rows = []
    for m in v["maps"]:
        cc, bc = m["cellCounts"], m["boxCounts"]
        order = ["wall", "floor", "lowCover", "highCover", "siteA", "siteB", "attackSpawn", "defenseSpawn"]
        rows.append([c_str(m["mapId"]), str(m["width"]), str(m["height"]), "{" + ",".join(str(cc[k]) for k in order) + "}", "{" + ",".join(str(bc[k]) for k in order) + "}"])
    table("FMapV", "GMaps", rows)
    table("FCenterV", "GCenters", [[c_str(m["mapId"]), str(c["x"]), str(c["y"]), repr(c["east"]), repr(c["north"])] for m in v["maps"] for c in m["centers"]])
    table("FCellAtV", "GCellAt", [[c_str(m["mapId"]), repr(c["east"]), repr(c["north"]), str(c["expectedX"]), str(c["expectedY"])] for m in v["maps"] for c in m["cellAt"]])
    table("FPathV", "GPaths", [[c_str(m["mapId"]), str(p["fromX"]), str(p["fromY"]), str(p["toX"]), str(p["toY"]), c_bool(p["found"]), repr(p["expectedCost"])] for m in v["maps"] for p in m["paths"]])
    table("FRngV", "GRng", [[str(r["seed"]) + "u", "{" + ",".join(str(x) + "u" for x in r["expectedInts"]) + "}", "{" + ",".join(repr(x) for x in r["expectedFloats"]) + "}"] for r in v["rng"]])
    table("FHashV", "GHash", [[c_str(h["text"]), str(h["expected"]) + "u"] for h in v["hash"]])
    table("FSynthV", "GSynth", [[c_str(s["cueId"]), str(s["sampleRate"]), str(s["expectedCount"]), "{" + ",".join(str(i) for i in s["indices"]) + "}", "{" + ",".join(repr(x) for x in s["expectedValues"]) + "}"] for s in v["synth"]])
    steps = []
    cases = []
    for c in v["shop"]:
        first = len(steps)
        for s in c["steps"]:
            steps.append([c_str(s["op"]), c_str(s["item"]), c_str(s["expectedResult"]), str(s["expectedMoney"]), c_str(s["expectedDropped"]),
                          c_str(s["expectedPrimary"]), c_str(s["expectedSecondary"]), str(s["expectedArmor"]), c_bool(s["expectedKit"]),
                          "{" + ",".join(str(x) for x in s["expectedCharges"]) + "}"])
        cases.append([c_str(c["name"]), c_str(c["agentId"]), c_str(c["side"]), str(c["initialMoney"]), c_str(c["initialPrimary"]), str(c["initialArmor"]), str(first), str(len(c["steps"]))])
    table("FShopStepV", "GShopSteps", steps)
    table("FShopCaseV", "GShopCases", cases)
    return "\n".join(o) + "\n"


os.makedirs(BUILD, exist_ok=True)
with open(os.path.join(BUILD, "generated_data.inc"), "w") as f:
    f.write(data_inc())
with open(os.path.join(BUILD, "generated_vectors.inc"), "w") as f:
    f.write(vectors_inc())
print("generated", os.path.relpath(BUILD))
